image: node:12-alpine

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - apk add git
    - npm install
  artifacts:
    paths:
      - node_modules/

testing_testing:
  stage: test
  script: 
    - npm run eslint
    - npm test
